### ISSUE TITLE
Can you share EFI ?

### ISSUE THREAD

**Issue by huynhchanhtin** [Yoshi2889/840g2-opencore-config#3]
Hi you, i can't boot with this 840g2-opencore-config, can you share your EFI ?
Thank you, so much !

**Comment by NanoSector** [comment]
Hi, what exactly are you having issues with? I will not be sharing a full EFI copy.

**Comment by huynhchanhtin** [comment]
i creat usb efi with your config Opencore 0.8.0 , but can't boot.

**Comment by NanoSector** [comment]
This doesn't help me, can you share logs?

**Comment by huynhchanhtin** [comment]
Thank you, your config run opencore 0.8.0
